groups:
- name: Prometheus Alerts
  rules:
  - alert: Prometheus AlertManager config not synced
    expr: 'count(count_values("config_hash", alertmanager_config_hash)) > 1'
    annotations:
      description: Configurations of AlertManager cluster instances are out of sync
    labels:
      severity: warning
  - alert: Prometheus target scraping slow
    expr: 'prometheus_target_interval_length_seconds{quantile="0.9"} > 60'
    annotations:
      description: Prometheus is scraping exporters slowly
    labels:
      severity: warning
    for: 5m

- name: Host and hardware
  rules:
  - alert: Host out of memory
    expr: 'node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10'
    annotations:
      description: Node memory is filling up (< 10% left)
    labels:
      severity: warning
    for: 2m
  - alert: Host out of disk space
    expr: '(node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and on (instance, device, mountpoint) node_filesystem_readonly == 0'
    annotations:
      description: Disk is almost full (< 10% left)
    labels:
      severity: warning
    for: 2m
  - alert: Host high CPU load
    expr: '100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80'
    annotations:
      description: CPU load is > 80%
    labels:
      severity: warning
  - alert: Host OOM kill detected
    expr: 'increase(node_vmstat_oom_kill[1m]) > 0'
    annotations:
      description: OOM kill detected
    labels:
      severity: warning
  - alert: Host clock skew
    expr: '(node_timex_offset_seconds > 0.05 and deriv(node_timex_offset_seconds[5m]) >= 0) or (node_timex_offset_seconds < -0.05 and deriv(node_timex_offset_seconds[5m]) <= 0)'
    annotations:
      description: 'Clock skew detected. Clock is out of sync.'
    labels:
      severity: warning
    for: 2m

- name: Website metrics
  rules:
  - alert: High number of active users
    expr: 'site_active_users > 1000'
    annotations:
      description: 'The number of active users on the site is high ({{ $value }} users)'
    labels:
      severity: warning
  - alert: Low number of active users
    expr: 'site_active_users < 10'
    annotations:
      description: 'The number of active users on the site is low ({{ $value }} users)'
    labels:
      severity: warning
  - alert: High response time
    expr: 'site_response_time_seconds > 2'
    annotations:
      description: 'The response time of the site is high ({{ $value }} seconds)'
    labels:
      severity: warning
    for: 2m
  - alert: High error rate
    expr: 'rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05'
    annotations:
      description: 'The error rate of the site is high ({{ $value }} errors per second)'
    labels:
      severity: critical
    for: 1m

- name: User Activity Alerts
  rules:
  - alert: Suspicious User Activity
    expr: 'rate(site_failed_login_attempts_total[1m]) > 10'
    annotations:
      description: Detected more than 10 failed login attempts per minute.
    labels:
      severity: critical

- name: Database Alerts
  rules:
  - alert: High Database CPU Usage
    expr: 'rate(node_cpu_seconds_total{job="db", mode!="idle"}[5m]) / rate(node_cpu_seconds_total{job="db"}[5m]) > 0.8'
    annotations:
      description: Database CPU usage exceeds 80%.
    labels:
      severity: warning
  - alert: High Database Query Time
    expr: 'rate(db_query_time_seconds_sum[5m]) / rate(db_query_time_seconds_count[5m]) > 0.5'
    annotations:
      description: Average query execution time to the database exceeds 500 ms.
    labels:
      severity: warning
  - alert: Low Database Disk Space
    expr: 'node_filesystem_avail_bytes{job="db"} / node_filesystem_size_bytes{job="db"} < 0.1'
    annotations:
      description: Remaining disk space in the database file system is less than 10%.
    labels:
      severity: warning

- name: Network Alerts
  rules:
  - alert: High Network Latency
    expr: 'rate(node_network_receive_errs_total[5m]) / rate(node_network_receive_packets_total[5m]) > 0.05'
    annotations:
      description: Network receive error rate exceeds 5%.
    labels:
      severity: warning
  - alert: High Network Load
    expr: 'rate(node_network_transmit_bytes_total[5m]) > 10000000'
    annotations:
      description: Network data transmission rate exceeds 10 MB/s.
    labels:
      severity: warning

- name: Container Alerts
  rules:
  - alert: Container Restarts
    expr: 'rate(container_restart_count[5m]) > 5'
    annotations:
      description: Container has restarted more than 5 times in the last 5 minutes.
    labels:
      severity: critical
