global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [192.168.0.100:9093]

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["192.168.0.101:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.0.101:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.0.101:8081"]

